Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,13 +20,12 @@ jobs:
         with:
           distribution: temurin
           java-version: 17
-          cache: gradle
 
       - name: Locate Android Project
         id: locate
         shell: bash
         run: |
-          GRADLEW=$(find . -type f -name gradlew | head -n 1)
+          GRADLEW=$(find . -type f -name "gradlew" | head -n 1)
 
           if [ -z "$GRADLEW" ]; then
             echo "::error::gradlew not found!"
@@ -35,6 +34,34 @@ jobs:
 
           chmod +x "$GRADLEW"
 
+          PROJECT_DIR=$(dirname "$GRADLEW")
+
+          echo "Project found: $PROJECT_DIR"
+
+          echo "project_dir=$PROJECT_DIR" >> $GITHUB_OUTPUT
+
+      - name: Build Debug APK
+        working-directory: ${{ steps.locate.outputs.project_dir }}
+        run: |
+          ./gradlew clean assembleDebug --stacktrace --no-daemon
+
+      - name: Verify APK Exists
+        run: |
+          APK=$(find . -type f -name "*.apk" | head -n 1)
+
+          if [ -z "$APK" ]; then
+            echo "::error::APK not found!"
+            exit 1
+          fi
+
+          echo "APK Found: $APK"
+
+      - name: Upload APK
+        uses: actions/upload-artifact@v4
+        with:
+          name: Rugda-Debug-APK
+          path: '**/build/outputs/apk/debug/*.apk'
+          if-no-files-found: error
           PROJECT_DIR=$(dirname "$GRADLEW")
 
           echo "Project: $PROJECT_DIR"
